apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  clusterIP: 172.20.2.20
  selector:
    app: products-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app
spec:
  selector:
    matchLabels:
      app: products-app
  replicas: 1
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
      - name: products-app
        image: ignaciomontero2022/products-service-example-test:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
